name: persisted_cache
version: 0.0.1+0
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0" #Dart SDK 2022-02-18
  flutter: ">=2.10.2"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.4.1
  hive_flutter: ^1.1.0

dependency_overrides: null

dev_dependencies:
  flutter_lints: ^1.0.4
  build_runner:
  test:

flutter:
  uses-material-design: true
  generate: false
