name: persisted_cache
version: 0.0.1+1
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0" #Dart SDK 2022-02-18
  flutter: ">=2.10.2"

dependencies:
  code_generation_annotation:
    git:
      url: https://github.com/GitHubStuff/code_generation.git
      path: packages/code_generation_annotation
  cupertino_icons: ^1.0.4
  extensions_package:
    git:
      url: https://github.com/GitHubStuff/extensions_package.git
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.4.1
  hive_flutter: ^1.1.0
  log:
    git:
      url: https://github.com/GitHubStuff/log.git
  json_annotation: ^4.4.0

dependency_overrides: null

dev_dependencies:
  build_runner:
  code_generation:
    git:
      url: https://github.com/GitHubStuff/code_generation.git
      path: packages/code_generation
  flutter_lints: ^1.0.4
  json_serializable:
  test:

flutter:
  uses-material-design: true
  generate: false
